### ISSUE TITLE
LTI 2.0 result service handler returns a 500 on LTI 1.3 blocks

### ISSUE THREAD

**Issue by feanil** [openedx/xblock-lti-consumer#709]
## Description

`result_service_handler` only works on blocks configured as LTI 1.1, but nothing stops an
LTI 1.3 block from being asked for it, and the failure mode is a 500 rather than a 404.

`lti_xblock.py:1577` calls `lti_consumer.set_outcome_service_url(...)` outside any `try`.
That method exists only on `LtiConsumer1p1`.  `LtiConsumer1p3`, `LtiAdvantageConsumer` and
`LtiProctoringConsumer` define none of `set_outcome_service_url`, `get_result`,
`verify_result_headers`, `delete_result` or `put_result`.  Returning a real
`LtiAdvantageConsumer` from `get_lti_consumer()` and calling the handler gives:

```
AttributeError: 'LtiAdvantageConsumer' object has no attribute 'set_outcome_service_url'
```

The same call with a real `LtiConsumer1p1` gets past that line.

The URL is discoverable, so this is reachable from outside.  `get_course_lti_endpoints` in
the platform (`lms/djangoapps/courseware/views/views.py:1381-1386`) enumerates every `lti`
and `lti_consumer` block in a course and publishes an
`lti_2_0_result_service_json_endpoint` for each one, with no LTI version filter.  An LTI
1.3 block's result service URL is therefore advertised to anyone who reads that endpoint,
and 500s when called.

## Expected behavior

A request to `result_service_handler` on a block whose resolved LTI version is not
`lti_1p1` should return 404, the same status the handler already returns for an
unparseable suffix and an unknown user.  `get_course_lti_endpoints` arguably should skip
non-1.1 blocks too, but the handler should be safe on its own either way.

## Verified against

xblock-lti-consumer master `66ee48da`, openedx-platform master `6cb1e4fd`, 2026-09-21.
Reproduced with a throwaway test that returned a real `LtiAdvantageConsumer` from
`get_lti_consumer()`.

Noticed while reviewing #701, which touches `_result_service_get`.  Not caused by that PR.
